font_family JetBrains Mono Nerd Font 
bold_font auto 
italic_font auto 
bold_italic_font auto 

detect_urls yes
font_size 12 
enable_ligatures yes
bell_on_tab "🔔"
cursor_text_color background
cursor_shape block

shell_integration  no-cursor

allow_remote_control yes

background_opacity 0.80

enable_audio_bell yes

#include ~/.cache/wal/colors-kitty.conf

# Colors
selection_foreground  #E57373
selection_background #6C5B7B

url_color #88C0D0
cursor #A3BE8C


# Added by Gogh
include colors.conf
