#! /bin/sh

/home/aamir/.config/polybar/launch.sh &

pgrep -x sxhkd > /dev/null || sxhkd &

pkill picom

bspc monitor -d 1 2 3 4 5 
picom --config ~/.config/picom/picom.conf -b
feh --randomize --bg-fill  /home/aamir/Pictures/myWallpaper &
#/home/aamir/.local/bin/newlook.sh &

bspc config top_padding 0 

bspc config border_width        4 
bspc config window_gap          5 
#bspc config top_padding         10
#bspc config bottom_padding      10
#bspc config left_padding        10
#bspc config right_padding       10
bspc config single_monocle      false 
bspc config focus_follows_pointer true
bspc config pointer_follows_focus true 
bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

#color
bspc config normal_border_color   "#D8DEF9"
bspc config active_border_color   "#c586c0" 
bspc config focused_border_color  "#61FFCA" 
bspc config presel_feedback_color "#646695" 

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

bspc config pointer_modifier mod1
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner
xsetroot -cursor_name left_ptr &

xrandr --output eDP-1 --brightness 0.5
